USE [InteractPayroll_00001]
GO

/****** Object:  Table [dbo].[COMPANY]    Script Date: 2020/10/14 06:11:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COMPANY](
	[COMPANY_NO] [int] NOT NULL,
	[COMPANY_DESC] [varchar](40) NULL,
	[TAX_REF_NO] [varchar](20) NULL,
	[GENERATE_EMPLOYEE_NUMBER_IND] [varchar](1) NULL,
	[OVERTIME1_RATE] [money] NULL,
	[OVERTIME2_RATE] [money] NULL,
	[OVERTIME3_RATE] [money] NULL,
	[SALARY_OVERTIME1_RATE] [money] NULL,
	[SALARY_OVERTIME2_RATE] [money] NULL,
	[SALARY_OVERTIME3_RATE] [money] NULL,
	[TEL_WORK] [varchar](15) NULL,
	[TEL_FAX] [varchar](15) NULL,
	[DIPLOMATIC_INDEMNITY_IND] [varchar](1) NULL,
	[SALARY_DOUBLE_CHEQUE_BIRTHDAY_IND] [varchar](1) NULL,
	[WAGE_RUN_IND] [varchar](1) NULL,
	[SALARY_RUN_IND] [varchar](1) NULL,
	[SDL_EXEMPT_IND] [varchar](1) NULL,
	[SDL_REF_NO] [varchar](12) NULL,
	[BANK_NO] [smallint] NULL,
	[BRANCH_CODE] [int] NULL,
	[ACCOUNT_NO] [bigint] NULL,
	[UIF_REF_NO] [varchar](10) NULL,
	[VAT_NO] [varchar](10) NULL,
	[PAYE_REF_NO] [varchar](10) NULL,
	[TRADE_CLASSIFICATION_CODE] [varchar](4) NULL,
	[EFILING_NAME] [varchar](30) NULL,
	[EFILING_SURNAME] [varchar](30) NULL,
	[EFILING_CONTACT_NO] [varchar](11) NULL,
	[EFILING_EMAIL] [varchar](70) NULL,
	[PAYSLIP_EMAIL] [varchar](70) NULL,
	[TIME_ATTENDANCE_RUN_IND] [varchar](1) NULL,
	[SIC7_GROUP_CODE] [varchar](5) NULL,
	[LEAVE_BEGIN_MONTH] [int] NULL,
	[FINGERPRINT_ENGINE] [varchar](50) NULL,
	[PAYROLL_RUN_USER_SIGNOFF_IND] [varchar](1) NULL,
	[PAYSLIP_COST_TO_COMPANY_IND] [varchar](1) NULL,
	[COMPANY_EMAIL_ADDR] [varchar](70) NULL,
	[CO_REG_NO] [varchar](15) NULL,
	[UI19_EMPLOYER_PERSON_NAME] [varchar](30) NULL,
	[UI19_EMPLOYER_PERSON_ID_NO] [varchar](20) NULL,
	[LOCKOUT_BREAKS_FACILITY_ON_CLOCK_IND] [varchar](1) NULL,
	[COMPANY_DEL_IND] [varchar](1) NULL,
	[USER_NO_NEW_RECORD] [int] NOT NULL,
	[DATETIME_NEW_RECORD] [datetime] NOT NULL,
	[USER_NO_UPDATE_RECORD] [int] NULL,
	[DATETIME_UPDATE_RECORD] [datetime] NULL,
	[USER_NO_DELETE_RECORD] [int] NULL,
	[DATETIME_DELETE_RECORD] [datetime] NULL,
 CONSTRAINT [PK_COMPANY] PRIMARY KEY CLUSTERED 
(
	[COMPANY_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [InteractPayroll_00001]
GO

/****** Object:  Table [dbo].[COMPANY_Audit]    Script Date: 2020/10/14 06:11:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COMPANY_Audit](
	[COMPANY_NO] [int] NOT NULL,
	[AUDIT_NO] [int] IDENTITY(1,1) NOT NULL,
	[COMPANY_DESC] [varchar](40) NULL,
	[TAX_REF_NO] [varchar](20) NULL,
	[GENERATE_EMPLOYEE_NUMBER_IND] [varchar](1) NULL,
	[OVERTIME1_RATE] [money] NULL,
	[OVERTIME2_RATE] [money] NULL,
	[OVERTIME3_RATE] [money] NULL,
	[SALARY_OVERTIME1_RATE] [money] NULL,
	[SALARY_OVERTIME2_RATE] [money] NULL,
	[SALARY_OVERTIME3_RATE] [money] NULL,
	[TEL_WORK] [varchar](15) NULL,
	[TEL_FAX] [varchar](15) NULL,
	[DIPLOMATIC_INDEMNITY_IND] [varchar](1) NULL,
	[SALARY_DOUBLE_CHEQUE_BIRTHDAY_IND] [varchar](1) NULL,
	[WAGE_RUN_IND] [varchar](1) NULL,
	[SALARY_RUN_IND] [varchar](1) NULL,
	[SDL_EXEMPT_IND] [varchar](1) NULL,
	[SDL_REF_NO] [varchar](12) NULL,
	[BANK_NO] [smallint] NULL,
	[BRANCH_CODE] [int] NULL,
	[ACCOUNT_NO] [bigint] NULL,
	[UIF_REF_NO] [varchar](10) NULL,
	[VAT_NO] [varchar](10) NULL,
	[PAYE_REF_NO] [varchar](10) NULL,
	[TRADE_CLASSIFICATION_CODE] [varchar](4) NULL,
	[EFILING_NAME] [varchar](30) NULL,
	[EFILING_SURNAME] [varchar](30) NULL,
	[EFILING_CONTACT_NO] [varchar](11) NULL,
	[EFILING_EMAIL] [varchar](70) NULL,
	[PAYSLIP_EMAIL] [varchar](70) NULL,
	[TIME_ATTENDANCE_RUN_IND] [varchar](1) NULL,
	[SIC7_GROUP_CODE] [varchar](5) NULL,
	[LEAVE_BEGIN_MONTH] [int] NULL,
	[FINGERPRINT_ENGINE] [varchar](50) NULL,
	[PAYROLL_RUN_USER_SIGNOFF_IND] [varchar](1) NULL,
	[PAYSLIP_COST_TO_COMPANY_IND] [varchar](1) NULL,
	[COMPANY_EMAIL_ADDR] [varchar](70) NULL,
	[CO_REG_NO] [varchar](15) NULL,
	[UI19_EMPLOYER_PERSON_NAME] [varchar](30) NULL,
	[UI19_EMPLOYER_PERSON_ID_NO] [varchar](20) NULL,
	[LOCKOUT_BREAKS_FACILITY_ON_CLOCK_IND] [varchar](1) NULL,
	[COMPANY_DEL_IND] [varchar](1) NULL,
	[USER_NO_NEW_RECORD] [int] NOT NULL,
	[DATETIME_NEW_RECORD] [datetime] NOT NULL,
	[USER_NO_UPDATE_RECORD] [int] NULL,
	[DATETIME_UPDATE_RECORD] [datetime] NULL,
	[USER_NO_DELETE_RECORD] [int] NULL,
	[DATETIME_DELETE_RECORD] [datetime] NULL,
 CONSTRAINT [PK_COMPANY_AUDIT] PRIMARY KEY CLUSTERED 
(
	[COMPANY_NO] ASC,
	[AUDIT_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

